baseURL = "https://logsontap.dev"
title = "LogsOnTap"
copyright = "MIT"

languageCode = "en-US"
enableRobotsTXT = true

# Google Analytics
#googleAnalytics = "UA-123-45"

[taxonomies]
  notebook = "notebooks"
  series = "series"
  tag = "tags"

[markup]
  [markup.highlight]
    #codeFences = true
    #noClasses = false
    style = "arduino"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # enable raw HTML in Markdown

[params]
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "Monday, January 2, 2006"  # if unset, default is "2006-01-02"
logo = ""  # if you have a logo png
slogan = ""
license = "MIT"  # CC License

[params.math]
enable = false  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "katex"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "dracula"
darkTheme = "xcode-dark"  # apply this theme in dark mode

[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/

[[params.nav.custom]]
title = "About"
url = "/about"

[[params.nav.custom]]
title = "Hugo"
url = "https://gohugo.io/"
